# Generated by Django 5.0.1 on 2024-01-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ktm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_foto', models.CharField(auto_created=models.CharField(max_length=13), max_length=13)),
                ('nim', models.CharField(max_length=13)),
                ('nama', models.CharField(max_length=80)),
                ('tempat_lahir', models.CharField(max_length=30)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=200)),
                ('kec', models.CharField(max_length=30)),
                ('kota', models.CharField(max_length=30)),
                ('no_telp', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('tgl_daftar', models.DateField(auto_now_add=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktm.jurusan')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktm.status')),
            ],
        ),
    ]
