# Generated by Django 5.0.1 on 2024-01-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='prodi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ktm',
            name='kec',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ktm',
            name='kota',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ktm',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ktm',
            name='nim',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ktm',
            name='no_foto',
            field=models.CharField(auto_created=models.CharField(max_length=15), max_length=13),
        ),
        migrations.AlterField(
            model_name='ktm',
            name='tempat_lahir',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
