# Generated by Django 5.0.1 on 2024-01-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktm', '0002_alter_jurusan_prodi_alter_ktm_kec_alter_ktm_kota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktm',
            name='no_foto',
            field=models.CharField(max_length=13),
        ),
    ]
